services:
  # PHP + Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - finance_network

   # PostgreSQL
  db:
    image: postgres:15
    container_name: finance_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anna0205
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finance_network
  # Nginx
  nginx:
    image: nginx:alpine
    container_name: finance_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  dbdata: 